[listen]
ip = "0.0.0.0"
port = 8001
ssl = false

[log]
debug = true
path = "/var/log/pinger.log"

[pinger]
default-interval = 120
default-probes = 3
updates-interval = 60
save-interval = 180
save-path = "/etc/pinger/hosts.json"
